// ============================================================================
// Daily progress digest
// ============================================================================
// Turns the free-text activity feed (field_crew_activity) into a structured,
// chart-friendly rollup for the trainer's daily huddle.
//
// The feed is plain English sentences generated by the crew actions, e.g.
//   "Climbing: L1 → L2."
//   "Training session: 5h — Stumpgrinding 2h, Climbing Removal 3h"
//   "Applicator's License: Passed."
//   "First Aid/CPR: completed 2026-05-30"
//   "Assigned Avant 528 Operator training."
//
// We classify each line by pattern so we can count and visualize it. The
// patterns mirror the strings built in src/app/crew/actions.ts — if those
// wordings change, update the matchers here too.
// ============================================================================

import { parseISO, subDays, format } from 'date-fns';
import type { ActivityEntry } from './crew-data';

export type ActivityKind =
  | 'skill_up'
  | 'skill_down'
  | 'hours'
  | 'completion'
  | 'assignment'
  | 'specialty'
  | 'other';

export type ClassifiedActivity = ActivityEntry & {
  kind: ActivityKind;
  /** Hours logged, for 'hours' entries. */
  hours: number | null;
  /** Skill levels for 'skill_up'/'skill_down'; 0 means unrated. */
  skillFrom: number | null;
  skillTo: number | null;
};

// "unrated", "L1", "L2", "L3" → 0..3
function levelToNumber(token: string): number {
  const t = token.trim().toLowerCase();
  if (t === 'unrated') return 0;
  const m = /^l([123])$/.exec(t);
  return m ? Number(m[1]) : 0;
}

const SKILL_CHANGE = /(unrated|l[123])\s*→\s*(unrated|l[123])/i;
const COMPLETION =
  /\b(completed|card received|passed|earned|certified|certificate)\b/i;

/** Classify a single activity description into a typed bucket. */
export function classifyDescription(description: string): {
  kind: ActivityKind;
  hours: number | null;
  skillFrom: number | null;
  skillTo: number | null;
} {
  const text = description ?? '';

  // Skill level change: "<Skill>: L1 → L2."
  const skill = SKILL_CHANGE.exec(text);
  if (skill) {
    const from = levelToNumber(skill[1]);
    const to = levelToNumber(skill[2]);
    return {
      kind: to >= from ? 'skill_up' : 'skill_down',
      hours: null,
      skillFrom: from,
      skillTo: to,
    };
  }

  // Training session: "Training session: 5h — ..."
  if (/^training session:/i.test(text.trim())) {
    const h = /(\d+(?:\.\d+)?)\s*h\b/.exec(text);
    return {
      kind: 'hours',
      hours: h ? Number(h[1]) : null,
      skillFrom: null,
      skillTo: null,
    };
  }

  if (COMPLETION.test(text)) {
    return { kind: 'completion', hours: null, skillFrom: null, skillTo: null };
  }
  if (/\b(un)?assigned\b/i.test(text)) {
    return { kind: 'assignment', hours: null, skillFrom: null, skillTo: null };
  }
  if (/specialty/i.test(text)) {
    return { kind: 'specialty', hours: null, skillFrom: null, skillTo: null };
  }
  return { kind: 'other', hours: null, skillFrom: null, skillTo: null };
}

export function classifyActivity(entry: ActivityEntry): ClassifiedActivity {
  return { ...entry, ...classifyDescription(entry.description) };
}

export type DayBucket = { date: string; count: number };
export type PersonCount = { slug: string; name: string; count: number };

export type ProgressDigest = {
  /** Window bounds (inclusive), YYYY-MM-DD. */
  fromDate: string;
  toDate: string;
  /** One bar per day, oldest → newest. */
  days: DayBucket[];
  /** Headline counts for the stat cards. */
  totals: {
    entries: number;
    skillUps: number;
    hours: number;
    completions: number;
    activeCrew: number;
  };
  skillUps: ClassifiedActivity[];
  completions: ClassifiedActivity[];
  hoursByPerson: PersonCount[]; // count field holds hours here
  perPerson: PersonCount[];
  /** One-sentence summary the trainer can read aloud or paste. */
  headline: string;
};

function plural(n: number, one: string, many = one + 's'): string {
  return `${n} ${n === 1 ? one : many}`;
}

/**
 * Build the digest from raw activity entries.
 *
 * `todayISO` is passed in (not read from the clock) so the page controls the
 * window and the function stays pure/testable.
 */
export function buildDigest(
  entries: ActivityEntry[],
  opts: { days: number; todayISO: string },
): ProgressDigest {
  const today = parseISO(opts.todayISO);
  const fromDate = format(subDays(today, opts.days - 1), 'yyyy-MM-dd');
  const toDate = opts.todayISO;

  // Day skeleton (oldest → newest), so empty days still show as zero bars.
  const days: DayBucket[] = [];
  for (let i = opts.days - 1; i >= 0; i--) {
    days.push({ date: format(subDays(today, i), 'yyyy-MM-dd'), count: 0 });
  }
  const dayIndex = new Map(days.map((d, i) => [d.date, i]));

  const classified = entries
    .filter((e) => e.occurred_on >= fromDate && e.occurred_on <= toDate)
    .map(classifyActivity);

  const skillUps: ClassifiedActivity[] = [];
  const completions: ClassifiedActivity[] = [];
  const hoursBySlug = new Map<string, PersonCount>();
  const perSlug = new Map<string, PersonCount>();
  let totalHours = 0;

  for (const c of classified) {
    const di = dayIndex.get(c.occurred_on);
    if (di !== undefined) days[di].count++;

    const p = perSlug.get(c.employee_slug) ?? {
      slug: c.employee_slug,
      name: c.employee_name,
      count: 0,
    };
    p.count++;
    perSlug.set(c.employee_slug, p);

    if (c.kind === 'skill_up') skillUps.push(c);
    else if (c.kind === 'completion') completions.push(c);
    else if (c.kind === 'hours' && c.hours) {
      totalHours += c.hours;
      const h = hoursBySlug.get(c.employee_slug) ?? {
        slug: c.employee_slug,
        name: c.employee_name,
        count: 0,
      };
      h.count += c.hours;
      hoursBySlug.set(c.employee_slug, h);
    }
  }

  const bySlugDesc = (a: PersonCount, b: PersonCount) =>
    b.count - a.count || a.name.localeCompare(b.name);

  const totals = {
    entries: classified.length,
    skillUps: skillUps.length,
    hours: Math.round(totalHours * 100) / 100,
    completions: completions.length,
    activeCrew: perSlug.size,
  };

  const headlineParts: string[] = [];
  if (totals.skillUps) headlineParts.push(plural(totals.skillUps, 'skill level-up'));
  if (totals.hours) headlineParts.push(`${totals.hours}h logged`);
  if (totals.completions)
    headlineParts.push(plural(totals.completions, 'completion'));
  const headline =
    totals.entries === 0
      ? 'No activity logged in the last 7 days.'
      : `Last 7 days: ${headlineParts.join(', ')} across ${plural(
          totals.activeCrew,
          'crew member',
        )}.`;

  return {
    fromDate,
    toDate,
    days,
    totals,
    skillUps,
    completions,
    hoursByPerson: Array.from(hoursBySlug.values()).sort(bySlugDesc),
    perPerson: Array.from(perSlug.values()).sort(bySlugDesc),
    headline,
  };
}
