// ============================================================================
// Daily progress digest
// ============================================================================
// Turns the free-text activity feed (field_crew_activity) into a structured,
// chart-friendly rollup for the trainer's daily huddle.
//
// The feed is plain English sentences generated by the crew actions + the
// grading SQL functions. The wordings we key off (keep in sync if they change
// in src/app/crew/actions.ts or the supabase migrations):
//   "Climbing: L1 → L2."                              → skill level-up
//   "Training session: 5h — Stumpgrinding 2h, ..."    → hours logged
//   "Certified on Avant 528 Operator — cert CERT-..." → certification (pass)
//   "Did not pass Avant 528 Operator — 12/20. ..."    → certification (fail)
//   "Applicator's License: Passed."  / ": Failed."    → certification pass/fail
//   "First Aid/CPR: completed 2026-05-30"             → training completion
//
// Dedup rule (per the trainer's ask): if someone FAILED and later PASSED the
// same certification inside the window, we only report the pass.
// ============================================================================

import { parseISO, subDays, format } from 'date-fns';
import type { ActivityEntry } from './crew-data';

export type ActivityKind =
  | 'skill_up'
  | 'skill_down'
  | 'hours'
  | 'cert_pass'
  | 'cert_fail'
  | 'assignment'
  | 'specialty'
  | 'other';

export type ClassifiedActivity = ActivityEntry & {
  kind: ActivityKind;
  /** Hours logged, for 'hours' entries. */
  hours: number | null;
  /** Skill levels for 'skill_up'/'skill_down'; 0 means unrated. */
  skillFrom: number | null;
  skillTo: number | null;
  /** Certification/training name, for 'cert_pass'/'cert_fail'. */
  certName: string | null;
};

// "unrated", "L1", "L2", "L3" → 0..3
function levelToNumber(token: string): number {
  const t = token.trim().toLowerCase();
  if (t === 'unrated') return 0;
  const m = /^l([123])$/.exec(t);
  return m ? Number(m[1]) : 0;
}

const SKILL_CHANGE = /(unrated|l[123])\s*→\s*(unrated|l[123])/i;
const CERTIFIED_ON = /^certified on (.+?) — cert /i;
const DID_NOT_PASS = /^did not pass (.+?) —/i;
const LICENSE = /^(applicator'?s license): (passed|failed)\b/i;
const TRAINING_DONE = /\b(?:completed|card received) \d{4}-\d{2}-\d{2}/i;

type Classification = Pick<
  ClassifiedActivity,
  'kind' | 'hours' | 'skillFrom' | 'skillTo' | 'certName'
>;

const base: Classification = {
  kind: 'other',
  hours: null,
  skillFrom: null,
  skillTo: null,
  certName: null,
};

/** Classify a single activity description into a typed bucket. */
export function classifyDescription(description: string): Classification {
  const text = (description ?? '').trim();

  // Skill level change: "<Skill>: L1 → L2."
  const skill = SKILL_CHANGE.exec(text);
  if (skill) {
    const from = levelToNumber(skill[1]);
    const to = levelToNumber(skill[2]);
    return { ...base, kind: to >= from ? 'skill_up' : 'skill_down', skillFrom: from, skillTo: to };
  }

  // Training session hours: "Training session: 5h — ..."
  if (/^training session:/i.test(text)) {
    const h = /(\d+(?:\.\d+)?)\s*h\b/.exec(text);
    return { ...base, kind: 'hours', hours: h ? Number(h[1]) : null };
  }

  // Module certification earned: "Certified on <Module> — cert CERT-..."
  const certified = CERTIFIED_ON.exec(text);
  if (certified) return { ...base, kind: 'cert_pass', certName: certified[1].trim() };

  // Module test failed: "Did not pass <Module> — 12/20. Retraining required."
  const failed = DID_NOT_PASS.exec(text);
  if (failed) return { ...base, kind: 'cert_fail', certName: failed[1].trim() };

  // Applicator's License pass/fail.
  const license = LICENSE.exec(text);
  if (license) {
    const isPass = license[2].toLowerCase() === 'passed';
    return { ...base, kind: isPass ? 'cert_pass' : 'cert_fail', certName: "Applicator's License" };
  }

  // Training record completion: "<Training>: completed 2026-05-30" (or card received).
  if (TRAINING_DONE.test(text)) {
    const name = /^(.+?):\s/.exec(text);
    return { ...base, kind: 'cert_pass', certName: name ? name[1].trim() : 'Training' };
  }

  if (/\b(un)?assigned\b/i.test(text)) return { ...base, kind: 'assignment' };
  if (/specialty/i.test(text)) return { ...base, kind: 'specialty' };
  return { ...base };
}

export function classifyActivity(entry: ActivityEntry): ClassifiedActivity {
  return { ...entry, ...classifyDescription(entry.description) };
}

export type DayBucket = { date: string; count: number };
export type PersonCount = { slug: string; name: string; count: number };
export type CertGroup = { name: string; count: number };
export type CertOutcome = ClassifiedActivity & { certName: string };

export type ProgressDigest = {
  /** Window bounds (inclusive), YYYY-MM-DD. */
  fromDate: string;
  toDate: string;
  /** One bar per day, oldest → newest. */
  days: DayBucket[];
  /** Specific, deduped report callouts. */
  callouts: {
    leveledUpPeople: number;
    leveledUpEvents: number;
    certifiedTotal: number;
    certifiedByCert: CertGroup[];
    failedTotal: number;
    failedByCert: CertGroup[];
    hours: number;
  };
  /** "Who moved the needle" — progress events per person, desc. */
  leaderboard: PersonCount[];
  skillUps: ClassifiedActivity[];
  certified: CertOutcome[];
  failed: CertOutcome[];
  hoursByPerson: PersonCount[];
  totalEntries: number;
};

function groupByCert(items: CertOutcome[]): CertGroup[] {
  const m = new Map<string, number>();
  for (const it of items) m.set(it.certName, (m.get(it.certName) ?? 0) + 1);
  return Array.from(m.entries())
    .map(([name, count]) => ({ name, count }))
    .sort((a, b) => b.count - a.count || a.name.localeCompare(b.name));
}

/**
 * Build the digest from raw activity entries (newest-first).
 *
 * `todayISO` is passed in (not read from the clock) so the page controls the
 * window and the function stays pure/testable.
 */
export function buildDigest(
  entries: ActivityEntry[],
  opts: { days: number; todayISO: string },
): ProgressDigest {
  const today = parseISO(opts.todayISO);
  const fromDate = format(subDays(today, opts.days - 1), 'yyyy-MM-dd');
  const toDate = opts.todayISO;

  // Day skeleton (oldest → newest) so empty days still show as zero bars.
  const days: DayBucket[] = [];
  for (let i = opts.days - 1; i >= 0; i--) {
    days.push({ date: format(subDays(today, i), 'yyyy-MM-dd'), count: 0 });
  }
  const dayIndex = new Map(days.map((d, i) => [d.date, i]));

  const classified = entries
    .filter((e) => e.occurred_on >= fromDate && e.occurred_on <= toDate)
    .map(classifyActivity);

  const skillUps: ClassifiedActivity[] = [];
  const leveledUpPeople = new Set<string>();
  const hoursBySlug = new Map<string, PersonCount>();
  const needleBySlug = new Map<string, PersonCount>();
  let totalHours = 0;

  // Cert dedup: a pass anywhere in the window beats a fail for the same
  // (person, cert). `*First` keeps the newest representative entry (entries
  // arrive newest-first, so the first one we see per key is the newest).
  const passKeys = new Set<string>();
  const passFirst = new Map<string, CertOutcome>();
  const failFirst = new Map<string, CertOutcome>();
  const keyOf = (c: ClassifiedActivity) => `${c.employee_slug}|${c.certName}`;

  const bumpNeedle = (c: ClassifiedActivity) => {
    const p = needleBySlug.get(c.employee_slug) ?? {
      slug: c.employee_slug,
      name: c.employee_name,
      count: 0,
    };
    p.count++;
    needleBySlug.set(c.employee_slug, p);
  };

  for (const c of classified) {
    const di = dayIndex.get(c.occurred_on);
    if (di !== undefined) days[di].count++;

    if (c.kind === 'skill_up') {
      skillUps.push(c);
      leveledUpPeople.add(c.employee_slug);
      bumpNeedle(c);
    } else if (c.kind === 'hours' && c.hours) {
      totalHours += c.hours;
      const h = hoursBySlug.get(c.employee_slug) ?? {
        slug: c.employee_slug,
        name: c.employee_name,
        count: 0,
      };
      h.count += c.hours;
      hoursBySlug.set(c.employee_slug, h);
      bumpNeedle(c);
    } else if (c.kind === 'cert_pass' && c.certName) {
      const key = keyOf(c);
      passKeys.add(key);
      if (!passFirst.has(key)) passFirst.set(key, c as CertOutcome);
      bumpNeedle(c);
    } else if (c.kind === 'cert_fail' && c.certName) {
      const key = keyOf(c);
      if (!failFirst.has(key)) failFirst.set(key, c as CertOutcome);
    }
  }

  const certified = Array.from(passFirst.values());
  const failed = Array.from(failFirst.entries())
    .filter(([key]) => !passKeys.has(key))
    .map(([, c]) => c);

  const bySlugDesc = (a: PersonCount, b: PersonCount) =>
    b.count - a.count || a.name.localeCompare(b.name);

  const round2 = (n: number) => Math.round(n * 100) / 100;

  return {
    fromDate,
    toDate,
    days,
    callouts: {
      leveledUpPeople: leveledUpPeople.size,
      leveledUpEvents: skillUps.length,
      certifiedTotal: certified.length,
      certifiedByCert: groupByCert(certified),
      failedTotal: failed.length,
      failedByCert: groupByCert(failed),
      hours: round2(totalHours),
    },
    leaderboard: Array.from(needleBySlug.values()).sort(bySlugDesc),
    skillUps,
    certified,
    failed,
    hoursByPerson: Array.from(hoursBySlug.values())
      .map((p) => ({ ...p, count: round2(p.count) }))
      .sort(bySlugDesc),
    totalEntries: classified.length,
  };
}
